{% set name = "llvm-spirv" %}
{% set version = "15.0.0" %}
{% set llvm_version = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/archive/v{{ version.replace("_", "-") }}.tar.gz
  sha256: b1bebd77f72988758c00852e78c2ddc545815a612169a0cb377d021e2f846d88

build:
  number: 0
  skip: true  # [not unix]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
  host:
    - llvmdev  {{ llvm_version }}.*
    - llvm  {{ llvm_version }}.*
    - zlib
  run_constrained:
    - llvmdev  {{ llvm_version }}.*

test:
  commands:
    - llvm-spirv -help

about:
  home: https://github.com/KhronosGroup/SPIRV-LLVM-Translator
  license: NCSA
  license_file: LICENSE.TXT
  license_family: BSD
  summary: A tool and a library for bi-directional translation between SPIR-V and LLVM IR

extra:
  recipe-maintainers:
    - isuruf
